test: Added test for rhc disconnect
RedHatInsights/rhc pull request #116
Opened 2024-05-27 09:48 UTC by Archana-PandeyM

2024-07-01 06:53 UTC, Archana-PandeyM commented
upstream tests are not using default insights-client.conf settings. 
One test failing upstream test_disconnect_when_already_disconnected, because default value of legacy_upload is True and output of "rhc disconnect" has different output for legacy and non legacy.
We decided that legacy upload will be discontinued and hence all downstream testing is non legacy.

2024-07-15 13:05 UTC, jirihnidek requested changes
Thanks for the PR. I can see that new test cause failure of integration tests. Please fix/remove failed test or if it is known issue of insights-client, then mark this test using `@pytest.mark.skip(reason="bug in insights-client CCT-XYZ")`. It is not possible to add new integration tests that are failing.

2024-07-29 15:12 UTC, Archana-PandeyM commented
/packit build

2024-09-24 13:50 UTC, Archana-PandeyM commented
/packit  test

2024-09-26 12:05 UTC, jirihnidek requested changes
Thanks for the update. :+1:  I think that one thing is not correct.

2024-09-26 12:05 UTC, jirihnidek commented on integration-tests/test_disconnect.py
> +    assert "Disconnected from Red Hat Insights" in disconnect_result.stdout
It does not seem correct. You check twice for a presence of "Disconnected from Red Hat Insights", but you do not check for a presence of string "Disconnected from Red Hat Subscription Management" in `stdout`.

2024-09-26 12:05 UTC, jirihnidek commented on integration-tests/test_disconnect.py
> +)
:+1:

2024-09-27 08:04 UTC, jirihnidek approved these changes
LGTM

2024-09-27 08:05 UTC, merged