fix: Report any unknown options found on the command line.
RedHatInsights/rhc pull request #159
Opened 2024-10-21 21:37 UTC by jvlcek

Card ID: CCT-524

The rhc subcommands, connect, disconnect and status ignore any unknown options given. This PR will fix this by returning an error when any unknown options are found.

The following tests were performed:

Test 1:  One unknown argument give.
```
% sudo  ./rhc connect activation-key 
error: unknown option(s): activation-key 
```

Test 2: Valid arguments given but unknown arguments were also given. The extra unknown
            arguments will produce an error.
```
% sudo  ./rhc connect --activation-key ${MY_KEY} --organization ${MY_ORG}  bobs your uncle
error: unknown option(s): bobs your uncle 

```

2024-10-21 21:40 UTC, Lorquas commented
Can one of the admins verify this patch?

2024-10-22 06:56 UTC, jirihnidek commented
/packit build

2024-10-22 08:00 UTC, jirihnidek requested changes
Thanks for the PR. I have few requests and suggestions.

2024-10-22 15:27 UTC, jvlcek commented on util.go
> +	return unknown_args
I believe this has been addressed by commit: https://github.com/RedHatInsights/rhc/pull/159/commits/af612bda5383dcd436448eb7810cb6fbb9e44427

2024-10-22 15:27 UTC, jvlcek commented on main.go
> +
I believe this has been addressed by commit: https://github.com/RedHatInsights/rhc/pull/159/commits/af612bda5383dcd436448eb7810cb6fbb9e44427

2024-10-22 15:27 UTC, jvlcek commented on main.go
> +	unknown_args := checkForUnknownArgs(ctx)
I believe this has been addressed by commit: https://github.com/RedHatInsights/rhc/pull/159/commits/af612bda5383dcd436448eb7810cb6fbb9e44427

2024-10-22 15:28 UTC, jvlcek commented on main.go
> +	unknown_args := checkForUnknownArgs(ctx)
I believe this has been addressed by commit: https://github.com/RedHatInsights/rhc/pull/159/commits/af612bda5383dcd436448eb7810cb6fbb9e44427

2024-10-22 15:34 UTC, jvlcek commented
@jirihnidek Let me know if you approve this version and I will squash my commits before it is merged.

Thank you again! Joe

2024-10-22 17:33 UTC, jvlcek commented
@jirihnidek I believe I've addressed all of the changes you have requested. Please let me know what you think now.

2024-10-23 08:10 UTC, jirihnidek approved these changes
LGTM, thanks for updates :+1:

2024-10-23 08:11 UTC, jirihnidek commented
/packit build

2024-10-23 08:23 UTC, merged

2024-10-23 10:37 UTC, jvlcek commented
Thank you for the help with this @jirihnidek