feat: Add --format json option for status sub-command
RedHatInsights/rhc pull request #26
Opened 2022-11-21 15:35 UTC by jirihnidek

* Sub-command status has now --json option. When this option is used, then status is printed to stdout at JSON document.
* JSON document always contains following items:
  - hostname
  - rhsm_connected
  - insights_connected
  - rhcd_running
* When something goes wrong, then JSON document can contain addition following items:
  - hostname_error
  - rhsm_error
  - insights_error
  - rhcd_error
* Example of JSON output can look like this:

```
[root@rhel9 ~]$ rhc status --json
{
    "hostname": "rhel9",
    "rhsm_connected": true,
    "insights_connected": false,
    "insights_error": {
        "Op": "fork/exec",
        "Path": "/usr/bin/insights-client",
        "Err": 2
    },
    "rhcd_running": false
}
```

2022-11-21 15:55 UTC, subpop commented
I like this idea. Can you make the flag a generic `--format` flag that expects the name of a format (i.e. `--format json` or `--format text`)? Using the value of the format (i.e. "json") as the flag name feels like an anti-pattern to me; "format" is the flag and "json" is the value. This way, as we increase the number of formats we support for output, we don't have to grow the if-else block with each new format. We can simple check the value of the "format" flag and act accordingly.

2022-11-21 17:07 UTC, jirihnidek commented
> I like this idea. Can you make the flag a generic `--format` flag that expects the name of a format (i.e. `--format json` or `--format text`)? Using the value of the format (i.e. "json") as the flag name feels like an anti-pattern to me; "format" is the flag and "json" is the value. This way, as we increase the number of formats we support for output, we don't have to grow the if-else block with each new format. We can simple check the value of the "format" flag and act accordingly.

Yes, it is possible to make a flag a generic and use `--format <format>`. On the other side isn't `--format <format>` overkill for such tool like `rhc`? Can you imagine that somebody will request to support XML, YAML, etc. in the future? BTW: Many tools uses only `--json` (e.g. command ip).

2022-11-23 10:50 UTC, jirihnidek commented
OK, I added another commit implementing pattern `--format <format>`. Only "json" is supported ATM.

2022-11-23 11:08 UTC, jirihnidek commented
Output could look like this:

```
[root@localhost ~]# rhc status --format json
{
    "hostname": "thinkpad-t580",
    "rhsm_connected": true,
    "insights_connected": false,
    "insights_error": {
        "Op": "fork/exec",
        "Path": "/usr/bin/insights-client",
        "Err": 2
    },
    "rhcd_running": false
}

[root@localhost ~]# rhc status --format xml
unsuported machine-readable format: xml (supported formats: "json")

[root@localhost ~]# rhc status --help
NAME:
   rhc status - Prints status of the system's connection to Red Hat

USAGE:
   rhc status

DESCRIPTION:
   The status command prints the state of the connection to Red Hat Subscription Management,
   Red Hat Insights and Red Hat.

OPTIONS:
   --format value, -f value  prints status in machine-readable format (supported formats: "json")
   --help, -h                show help (default: false)
```

2022-11-23 17:17 UTC, subpop requested changes
I like the approach of using a different print func depending on the format value. I have a crazy idea though. Could we normalize the "text" status output into a "printTextStatus" function that has a signature identical to the "printJSONStatus" function?

You could even define it as a type:

```go
type PrintFunc func(ch <-chan *SystemStatus) error
```

Then define two functions:

```go
// printJSONStatus receieves values from ch, marshals them to JSON and prints them.
func printJSONStatus(ch <- chan *SystemStatus) error {
    for status := range ch {
        data, err := json.MarshalIndent(status, "", "    ")
        if err != nil {
            return err
        }
        fmt.Println(string(data))
        return nil
    }
}

// printTextStatus prints status in a human-readable format.
func printTextStatus(ch chan <- *SystemStatus) error {
    for status := range ch {
        // Here we'd need to figure out a neat way to print just non-zero values from the
        // status values received over the channel.
    }
}
```

Change the format flag to set a default value of "text".

```go
&cli.StringFlag{
    Name:   "format",
    Usage:   `prints status in machine-readable format (supported formats: "json", "text")`,
    Aliases: []string{"f"},
    Value:   "text",
}
```

This would allow you to remove the `machineReadable` boolean, consolidating all the printing into the two PrintFuncs. In the `statusAction`,

```go
var printFunc PrintFunc
switch ctx.String("format") {
case "json":
    printFunc = printJSONStatus
case "text":
    printFunc = printTextStatus
default:
    err := fmt.Errorf("unsupported machine-readable format: %v (supported formats: %v)", format, `"json", "text"`)
    return cli.Exit(err, 1)
}
```

Once `printFunc` has been set to a valid `PrintFunc` create a channel and call `printFunc` on a goroutine.

```go
statusUpdates := make(chan *SystemStatus)
go printFunc(statusUpdates)
```

Now we can run through the status checks, sending each result to the channel.

```go
uuid, err := getConsumerUUID()
statusUpdates <- &SystemStatus{RHSMConnected: uuid != ""}

isRegistered, err := insightsIsRegistered()
statusUpdates <- &SystemStatus{InsightsConnected: isRegistered}
```

The `printFunc` implementation can either hold all the received *SystemStatus values and print them once the channel closes or can print them as they arrive.

2022-11-23 18:19 UTC, jirihnidek commented
> > Yes, it is possible to make a flag a generic and use `--format <format>`. On the other side isn't `--format <format>` overkill for such tool like `rhc`? Can you imagine that somebody will request to support XML, YAML, etc. in the future? BTW: Many tools uses only `--json` (e.g. command ip).
> 
> Sorry I didn't respond sooner. I hope you didn't take this as a silent disapproval of this approach. It probably is overkill for `rhc`, but as `rhc` grows from a "just shells out to a couple of programs" to a more feature-rich front-end client program, we might find that adding support for another format or two is reasonable. Perhaps inspecting and printing the known D-Bus interfaces, for example?

No problem, I added current change as another commit. Thus it is possible to go back if it will be necessary.

2022-11-23 18:20 UTC, jirihnidek commented on main.go
> +		defer func(systemStatus *SystemStatus) {
Thanks, but GoLand suggested this change ;-)

2022-11-23 18:21 UTC, jirihnidek commented on main.go
> +				)
OK, but I can see not that we should not use JSON in the message, but something more general.

2022-11-29 08:52 UTC, jirihnidek commented
I'm also thinking about the concept of adding this option (`--format json`) for all sub-commands, when all required data are provided using CLI options and there is no need of interaction with user. If this idea will be approved, then this should be part of another PR.

2022-11-29 15:55 UTC, subpop requested changes
Two very trivial things remain:

 * `goimports` needs to be run on `main.go` to format the imports
 * `go mod tidy` should be run because `golang.org/x/sys` is now directly imported

2022-11-29 21:24 UTC, jirihnidek commented
> Two very trivial things remain:
> 
>     * `goimports` needs to be run on `main.go` to format the imports
> 
>     * `go mod tidy` should be run because `golang.org/x/sys` is now directly imported

Updated.

2022-11-30 18:37 UTC, subpop commented
Farts. I really bunged this PR up trying to get rid of that merge commit.

2022-11-30 18:45 UTC, subpop commented
Looks great!

2022-11-30 18:46 UTC, merged