fix: http proxy configuration
RedHatInsights/rhc pull request #40
Opened 2023-07-18 14:39 UTC by ahitacat

HTTPClient was setting a custom transport instead of using the Default, leading to a unconfigured proxy from environment variables.

This commit modifies the default transport to use the proxy env variables.

Resolves: [RHBZ#2223405](https://bugzilla.redhat.com/show_bug.cgi?id=2223405)

2023-07-18 14:54 UTC, subpop approved these changes
LGTM

2023-07-19 08:09 UTC, jirihnidek requested changes
LGTM. I have only two small requests.

2023-07-19 08:09 UTC, jirihnidek commented on internal/http/client.go
> -		},
I would add here some comment here explaining why the client is created in this way.

2023-07-19 14:29 UTC, ahitacat commented on main.go
> +	/* 2. Register insights-client*/
Good catch! I didn't notice the lack of the space :rocket:

2023-07-19 14:31 UTC, ahitacat commented
# Changes
- Addressed @jirihnidek 's comment:
   - Added the space that was removed in a prior change.
   - Added some comments to give an explanation about the use of the defaultTransporter.

2023-07-19 14:34 UTC, jirihnidek approved these changes
LGTM, Thanks for updates.

2023-07-19 14:34 UTC, merged